[SA-1282] Fix: adding force orientation support to SideMenuController
Hectre/SideMenuController pull request #1
Opened 2022-12-02 05:58 UTC by dilumdesilva

## What's changed
As this view controller is the rootViewController for most of the viewControllers in the Hectre app, SideMenuController has been modified to support force orientations via this change.

podspec version has been updated to `0.24` => `0.2.5` 

## Deployment notes
- As this pod was cloned to Hectre organisation app `Podfile` requires path changes
- Update app pod and local pods for SideMenuController using `pod update SideMenuController`

2022-12-04 21:07 UTC, ariburgos requested changes

2022-12-04 21:07 UTC, ariburgos commented on Source/SideMenuController.swift
> +        return orientationLock ?? .all
Is this optional required? Looks like orientationLock is not optional

2022-12-04 21:07 UTC, ariburgos commented on Source/SideMenuController.swift
> +    /**
Are these line properly indented or is it just GitHub?

2022-12-04 21:07 UTC, ariburgos commented on Source/SideMenuController.swift
> +    open override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
This should go outside the scope of the` // MARK: - Public methods -` (line 32).

Add it into the main class or create a new extension to handle the orientation.

2022-12-04 21:07 UTC, ariburgos commented on Source/SideMenuController.swift
> +    private var orientationLock = UIInterfaceOrientationMask.all
indentation?

2022-12-05 00:21 UTC, dilumdesilva commented on Source/SideMenuController.swift
> +        return orientationLock ?? .all
Yes, I will remove the optional handling.

2022-12-05 00:21 UTC, dilumdesilva commented on Source/SideMenuController.swift
> +    /**
Let me check on this.

2022-12-05 00:23 UTC, dilumdesilva commented on Source/SideMenuController.swift
> +        return orientationLock ?? .all
Fixed

2022-12-05 00:24 UTC, dilumdesilva commented on Source/SideMenuController.swift
> +    /**
Indentation was fixed for the entire file

2022-12-05 00:25 UTC, dilumdesilva commented on Source/SideMenuController.swift
> +    private var orientationLock = UIInterfaceOrientationMask.all
Fixed for the entire file

2022-12-05 00:31 UTC, dilumdesilva commented on Source/SideMenuController.swift
> +    open override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
Moved it into the class

2022-12-05 01:29 UTC, ariburgos approved these changes
Looking great 🚀

2022-12-05 01:31 UTC, merged